Repository anonymousOrmi/simsasookbak, pull requests merged in 2024-05, with the labels that each got.

#19 Feature/details page
  build.gradle
  src/main/java/com/simsasookbak/accommodation/controller/accommodationController.java
  src/main/java/com/simsasookbak/accommodation/domain/Accommodation.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/style.css
  src/main/resources/static/img/alan.png
  src/main/resources/static/lib/owlcarousel/assets/owl.carousel.min.css
  src/main/resources/static/lib/owlcarousel/owl.carousel.min.js
  src/main/resources/templates/details.html
  src/main/resources/templates/fragment/navigation-bar.html
  src/main/resources/templates/index.html
Labels: feat🚀

#21 Feature/search
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/domain/Accommodation.java
  src/main/java/com/simsasookbak/accommodation/dto/AccommodationDto.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/java/com/simsasookbak/room/domain/Room.java
  src/main/resources/data.sql
  src/main/resources/static/css/index.css
  src/main/resources/templates/index.html
Labels: feat🚀

#23 feat[#22] 유튜브 API 기능 구현
  build.gradle
  src/main/java/com/simsasookbak/external/youtube/controller/YoutubeController.java
  src/main/java/com/simsasookbak/external/youtube/dto/YoutubeProperties.java
  src/main/java/com/simsasookbak/external/youtube/dto/response/YouTubeResponse.java
  src/main/java/com/simsasookbak/external/youtube/service/YoutubeService.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
Labels: feat🚀

#24 AccommodationController, DATA.SQL merge
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/controller/accommodationController.java
  src/main/resources/data.sql
Labels: bug

#25 feat[#22] : Youtube API 연동
  src/main/java/com/simsasookbak/external/youtube/controller/YoutubeController.java
  src/main/java/com/simsasookbak/external/youtube/domain/Youtube.java
  src/main/java/com/simsasookbak/external/youtube/dto/YoutubeProperties.java
  src/main/java/com/simsasookbak/external/youtube/dto/response/YouTubeResponse.java
  src/main/java/com/simsasookbak/external/youtube/exception/YoutubeExceptionHandler.java
  src/main/java/com/simsasookbak/external/youtube/repository/YoutubeRepository.java
  src/main/java/com/simsasookbak/external/youtube/service/YoutubeService.java
  src/main/java/com/simsasookbak/global/BaseEntity.java
  src/main/java/com/simsasookbak/global/exception/ErrorMessage.java
  src/main/java/com/simsasookbak/global/exception/ErrorResponse.java
  src/main/java/com/simsasookbak/global/exception/GlobalExceptionHandler.java
  src/main/resources/static/js/common/datepicker.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/fragment/footer.html
  src/main/resources/templates/fragment/head.html
  src/main/resources/templates/index.html
Labels: feat🚀

#27 feat: [#18] 상세 페이지 연결
  build.gradle
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationRestController.java
  src/main/java/com/simsasookbak/accommodation/domain/AccommodationImage.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/java/com/simsasookbak/global/aop/PerformanceLoggingAspect.java
  src/main/java/com/simsasookbak/global/page/controller/NavbarController.java
  src/main/java/com/simsasookbak/review/controller/ReviewController.java
  src/main/java/com/simsasookbak/review/repository/ReviewRepository.java
  src/main/java/com/simsasookbak/review/service/ReviewService.java
  src/main/java/com/simsasookbak/room/controller/RoomController.java
  src/main/java/com/simsasookbak/room/dto/RoomDto.java
  src/main/java/com/simsasookbak/room/repository/RoomRepository.java
  src/main/java/com/simsasookbak/room/service/RoomService.java
  src/main/resources/data.sql
  src/main/resources/templates/details.html
  src/main/resources/templates/fragment/navigation-bar.html
  src/main/resources/templates/my-accommodation-list.html
Labels: enhancement, feat🚀

#28 feat : 메인 검색 기능
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/domain/Accommodation.java
  src/main/java/com/simsasookbak/accommodation/dto/AccommodationDto.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
  src/main/java/com/simsasookbak/room/repository/RoomRepository.java
  src/main/resources/data.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/reservationPage.html
Labels: feat🚀

#29 Bug: data.sql datetime(6)호환 문제 해결
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationRestController.java
  src/main/java/com/simsasookbak/accommodation/domain/Accommodation.java
  src/main/java/com/simsasookbak/accommodation/dto/AccommodationDto.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
  src/main/resources/data.sql
Labels: bug

#32 refactor : baseEntity 관련 타입 변경
  src/main/java/com/simsasookbak/global/BaseEntity.java
  src/main/resources/data.sql
Labels: refactor 🛠️

#36 feat[#35] 메인 인기지역 Top6 조회
  src/main/java/com/simsasookbak/accommodation/domain/Accommodation.java
  src/main/java/com/simsasookbak/reservation/controller/ReservationController.java
  src/main/java/com/simsasookbak/reservation/domain/Reservation.java
  src/main/java/com/simsasookbak/reservation/dto/request/PopularRegionRequest.java
  src/main/java/com/simsasookbak/reservation/dto/response/ReservationResponse.java
  src/main/java/com/simsasookbak/reservation/dto/response/ReservationView.java
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
  src/main/java/com/simsasookbak/reservation/service/ReservationService.java
  src/main/resources/static/js/popularRegion.js
  src/main/resources/templates/index.html
Labels: feat🚀

#38 feat[#37] 숙소 목록 조회 기능
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationRestController.java
  src/main/java/com/simsasookbak/accommodation/domain/Accommodation.java
  src/main/java/com/simsasookbak/accommodation/dto/AccommodationDto.java
  src/main/java/com/simsasookbak/accommodation/dto/request/AccommodationRequest.java
  src/main/java/com/simsasookbak/accommodation/dto/response/AccommodationResponse.java
  src/main/java/com/simsasookbak/accommodation/dto/response/AccommodationView.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/java/com/simsasookbak/external/youtube/dto/response/YouTubeResponse.java
  src/main/java/com/simsasookbak/member/domain/Member.java
  src/main/java/com/simsasookbak/reservation/domain/Reservation.java
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
  src/main/java/com/simsasookbak/room/domain/Room.java
  src/main/resources/data.sql
  src/main/resources/static/js/common/datepicker.js
  src/main/resources/static/js/popularRegion.js
  src/main/resources/templates/accommodation-register.html
  src/main/resources/templates/details.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/head.html
  src/main/resources/templates/layout/navigation-bar.html
  src/main/resources/templates/layout/top-bar.html
  src/main/resources/templates/my-accommodation-list.html
  src/main/resources/templates/review-register.html
Labels: feat🚀

#39 feat[30] 별점 기반 숙소 추천 구현
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/java/com/simsasookbak/global/page/controller/MainPageController.java
  src/main/java/com/simsasookbak/review/dto/ScoreAverageDto.java
  src/main/java/com/simsasookbak/review/repository/ReviewRepository.java
  src/main/java/com/simsasookbak/review/service/ReviewService.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
Labels: feat🚀

#43 fix : 병합 충돌 해결 버전
  src/main/java/com/simsasookbak/accommodation/dto/AccommodationDto.java
  src/main/java/com/simsasookbak/global/page/controller/PageController.java
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
  src/main/java/com/simsasookbak/review/repository/ReviewRepository.java
Labels: bug

#44 feat: 상세페이지 구현 및 브랜치 최신화
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/domain/Accommodation.java
  src/main/java/com/simsasookbak/accommodation/domain/AccommodationFacility.java
  src/main/java/com/simsasookbak/accommodation/domain/AccommodationFacilityMapping.java
  src/main/java/com/simsasookbak/accommodation/domain/AccommodationImage.java
  src/main/java/com/simsasookbak/accommodation/dto/AccommodationDto.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/java/com/simsasookbak/global/BaseEntity.java
  src/main/java/com/simsasookbak/review/domain/Review.java
  src/main/java/com/simsasookbak/review/dto/ReviewDto.java
  src/main/java/com/simsasookbak/review/repository/ReviewRepository.java
  src/main/java/com/simsasookbak/review/service/ReviewService.java
  src/main/java/com/simsasookbak/room/domain/Room.java
  src/main/java/com/simsasookbak/room/domain/RoomFacilityMapping.java
  src/main/java/com/simsasookbak/room/domain/RoomFacilityMappingId.java
  src/main/java/com/simsasookbak/room/dto/RoomDto.java
  src/main/java/com/simsasookbak/room/repository/RoomRepository.java
  src/main/java/com/simsasookbak/room/service/RoomService.java
  src/main/resources/data.sql
  src/main/resources/templates/details.html
  src/main/resources/templates/reservationPage.html
Labels: feat🚀

#49 feat: 로그인 로그아웃
  .gitignore
  data.sql
  src/main/java/com/simsasookbak/SimsasookbakApplication.java
  src/main/java/com/simsasookbak/global/config/WebSecurityConfig.java
  src/main/java/com/simsasookbak/member/controller/MemberController.java
  src/main/java/com/simsasookbak/member/domain/AddUserDto.java
  src/main/java/com/simsasookbak/member/domain/Member.java
  src/main/java/com/simsasookbak/member/domain/RegisterDto.java
  src/main/java/com/simsasookbak/member/repository/MemberRepository.java
  src/main/java/com/simsasookbak/member/service/MemberService.java
  src/main/java/com/simsasookbak/member/service/UserDetailService.java
  src/main/resources/static/css/register.css
  src/main/resources/static/img/login-background-img.jpg
  src/main/resources/static/js/register.js
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/top-bar.html
  src/main/resources/templates/login.html
Labels: feat🚀

#50 feat: 비번 암호화
  src/main/resources/data.sql
Labels: enhancement, feat🚀

#51 feat: 별점기반 숙소 추천
  src/main/java/com/simsasookbak/accommodation/dto/AccommodationDto.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/java/com/simsasookbak/review/service/ReviewService.java
  src/main/resources/data.sql
  src/main/resources/static/js/review.js
  src/main/resources/templates/details.html
  src/main/resources/templates/index.html
Labels: enhancement, feat🚀

#52 feat[#41] : Spring Scheduler를 통한 예약 상태 변경
  src/main/java/com/simsasookbak/global/config/SchedulingConfig.java
  src/main/java/com/simsasookbak/global/exception/ErrorMessage.java
  src/main/java/com/simsasookbak/reservation/domain/Status.java
  src/main/java/com/simsasookbak/reservation/dto/response/ReservationResponse.java
  src/main/java/com/simsasookbak/reservation/dto/response/ReservationView.java
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
  src/main/java/com/simsasookbak/reservation/scheduling/ReservationStatusTask.java
  src/main/java/com/simsasookbak/reservation/service/ReservationService.java
  src/main/resources/application.yml
Labels: feat🚀

#53 feat[#45] : 앨런 연동하기
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/external/ai/alan/config/AlanConfig.java
  src/main/java/com/simsasookbak/external/ai/alan/controller/AlanController.java
  src/main/java/com/simsasookbak/external/ai/alan/controller/AlanEventListener.java
  src/main/java/com/simsasookbak/external/ai/alan/dto/AlanResponseDto.java
  src/main/java/com/simsasookbak/external/ai/alan/event/RegistrationEvent.java
  src/main/java/com/simsasookbak/external/ai/alan/service/AlanService.java
  src/main/java/com/simsasookbak/global/config/WebSecurityConfig.java
  src/main/java/com/simsasookbak/member/service/MemberService.java
  src/main/java/com/simsasookbak/reservation/controller/ReservationController.java
  src/main/java/com/simsasookbak/review/domain/ExternalSummary.java
  src/main/java/com/simsasookbak/review/dto/ExternalSummaryRequest.java
  src/main/java/com/simsasookbak/review/dto/ExternalSummaryResponse.java
  src/main/java/com/simsasookbak/review/repository/ExternalSummaryRepository.java
  src/main/java/com/simsasookbak/review/repository/ReviewRepository.java
  src/main/java/com/simsasookbak/review/service/ExternalSummaryService.java
  src/main/java/com/simsasookbak/review/service/ReviewService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/templates/reservationPage.html
Labels: feat🚀

#56 feat[#54] : 목록 페이지 구현
  data.sql
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/resources/templates/list-page.html
Labels: feat🚀

#57 refactor[#58]: main.js 내 메인 화면 youtube api 호출 분리
  src/main/resources/static/js/index.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/index.html
Labels: refactor 🛠️

#62 feat[#54] : 숙소 찾기
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/navigation-bar.html
  src/main/resources/templates/list-page.html
Labels: feat🚀

#63 feat : 예약 내역 조회
  src/main/java/com/simsasookbak/reservation/controller/ReservationController.java
  src/main/java/com/simsasookbak/reservation/dto/response/ReservationResponseDto.java
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
  src/main/java/com/simsasookbak/reservation/service/ReservationService.java
  src/main/resources/static/js/reservationList.js
  src/main/resources/templates/layout/navigation-bar.html
  src/main/resources/templates/my-reservation-list.html
  src/main/resources/templates/reservation-detail.html
Labels: enhancement, feat🚀

#66 feat : my reservation
  src/main/java/com/simsasookbak/reservation/controller/ReservationApiController.java
  src/main/java/com/simsasookbak/reservation/controller/ReservationController.java
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
  src/main/java/com/simsasookbak/reservation/service/ReservationService.java
  src/main/resources/static/js/reservationList.js
  src/main/resources/templates/my-reservation-list.html
  src/main/resources/templates/reservation-detail.html
Labels: enhancement, feat🚀

#67 feat: review register
  build.gradle
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/global/config/S3Config.java
  src/main/java/com/simsasookbak/member/domain/Member.java
  src/main/java/com/simsasookbak/reservation/service/ReservationService.java
  src/main/java/com/simsasookbak/review/controller/ReviewController.java
  src/main/java/com/simsasookbak/review/domain/Review.java
  src/main/java/com/simsasookbak/review/domain/ReviewImage.java
  src/main/java/com/simsasookbak/review/dto/ReviewDto.java
  src/main/java/com/simsasookbak/review/repository/ReviewImageRepository.java
  src/main/java/com/simsasookbak/review/service/ReviewService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/templates/details.html
  src/main/resources/templates/review-register.html
Labels: enhancement, feat🚀

#71 feat[#45] 숙소,시설,객실,시설,앨런 등등..
  src/main/java/com/simsasookbak/SimsasookbakApplication.java
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/domain/AccommodationFacilityMapping.java
  src/main/java/com/simsasookbak/accommodation/dto/request/AccommodationAddRequestDto.java
  src/main/java/com/simsasookbak/accommodation/dto/request/AccommodationAndRoomsAddRequestDto.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationFacilityMappingRepository.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationFacilityRepository.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationFacilityMappingService.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationFacilityService.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/java/com/simsasookbak/external/ai/alan/controller/AlanEventListener.java
  src/main/java/com/simsasookbak/external/ai/alan/service/AlanService.java
  src/main/java/com/simsasookbak/global/config/AsyncConfig.java
  src/main/java/com/simsasookbak/global/page/controller/PageController.java
  src/main/java/com/simsasookbak/reservation/controller/ReservationController.java
  src/main/java/com/simsasookbak/reservation/dto/ReservationAddRequestDto.java
  src/main/java/com/simsasookbak/reservation/service/ReservationService.java
  src/main/java/com/simsasookbak/room/controller/RoomController.java
  src/main/java/com/simsasookbak/room/domain/RoomFacilityMapping.java
  src/main/java/com/simsasookbak/room/domain/RoomFacilityMappingId.java
  src/main/java/com/simsasookbak/room/dto/RoomAddRequestDto.java
  src/main/java/com/simsasookbak/room/repository/RoomFacilityMappingRepository.java
  src/main/java/com/simsasookbak/room/repository/RoomFacilityRepository.java
  src/main/java/com/simsasookbak/room/repository/RoomRepository.java
  src/main/java/com/simsasookbak/room/service/RoomFacilityMappingService.java
  src/main/java/com/simsasookbak/room/service/RoomFacilityService.java
  src/main/java/com/simsasookbak/room/service/RoomService.java
  src/main/resources/data.sql
  src/main/resources/templates/accommodation-register.html
  src/main/resources/templates/accommodation-update.html
  src/main/resources/templates/details.html
Labels: enhancement, feat🚀

#68 feat[#64] 예약 취소/확정 시, 이메일 발송
  build.gradle
  src/main/java/com/simsasookbak/email/domain/MailType.java
  src/main/java/com/simsasookbak/email/dto/MailForm.java
  src/main/java/com/simsasookbak/email/service/MailService.java
  src/main/java/com/simsasookbak/global/exception/ErrorMessage.java
  src/main/java/com/simsasookbak/member/domain/Role.java
  src/main/java/com/simsasookbak/reservation/controller/ReservationApiController.java
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
  src/main/java/com/simsasookbak/reservation/service/ReservationService.java
  src/main/resources/application.yml
  src/main/resources/templates/layout/mailForm.html
Labels: feat🚀

#74 feat[#73] 등록된 숙소 조회, 예약 내역 조회
  src/main/java/com/simsasookbak/accommodation/dto/response/AccommodationRegisteredResponse.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/java/com/simsasookbak/global/page/controller/NavbarController.java
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
  src/main/java/com/simsasookbak/reservation/service/ReservationService.java
  src/main/resources/templates/layout/navigation-bar.html
  src/main/resources/templates/my-accommodation-list.html
  src/main/resources/templates/reservation-management.html
Labels: feat🚀

#76 refactor : 불필요한 조건제거
  src/main/java/com/simsasookbak/email/domain/MailType.java
  src/main/java/com/simsasookbak/email/dto/MailForm.java
  src/main/java/com/simsasookbak/reservation/controller/ReservationApiController.java
  src/main/java/com/simsasookbak/reservation/service/ReservationService.java
  src/main/resources/templates/layout/mailForm.html
Labels: refactor 🛠️

#77 fix : 리뷰 등록 가능 방 중복 데이터 제거
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
  src/main/java/com/simsasookbak/reservation/service/ReservationService.java
Labels: bug

#80 refactor : 숙소 등록 화면 공통 레이아웃 적용
  src/main/resources/templates/accommodation-register.html
Labels: bug, refactor 🛠️

#82 refactor : 간단한 입력 input 타입 변경
  src/main/resources/templates/accommodation-register.html
Labels: bug, refactor 🛠️

#84 feat : 숙소 수정, 객실 수정
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/domain/Accommodation.java
  src/main/java/com/simsasookbak/accommodation/domain/AccommodationFacility.java
  src/main/java/com/simsasookbak/accommodation/dto/AccommodationUpdateDto.java
  src/main/java/com/simsasookbak/accommodation/dto/response/AccommodationAddResponseDto.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationFacilityMappingRepository.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationFacilityMappingService.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationFacilityService.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/java/com/simsasookbak/global/page/controller/PageController.java
  src/main/java/com/simsasookbak/room/controller/RoomController.java
  src/main/java/com/simsasookbak/room/domain/Room.java
  src/main/java/com/simsasookbak/room/dto/RoomUpdateDto.java
  src/main/java/com/simsasookbak/room/repository/RoomFacilityMappingRepository.java
  src/main/java/com/simsasookbak/room/service/RoomFacilityMappingService.java
  src/main/java/com/simsasookbak/room/service/RoomService.java
  src/main/resources/templates/accommodation-update.html
  src/main/resources/templates/details.html
  src/main/resources/templates/room-update.html
Labels: enhancement, feat🚀

#89 fix : 키워드 검색 시, 숙소 명 추가
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
Labels: bug

#88 comment : "메인페이지 인기 숙소 별점 추가"
  src/main/java/com/simsasookbak/accommodation/dto/AccommodationDto.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/resources/templates/index.html
Labels: feat🚀

#91 refactor : 화면 수정
  src/main/resources/templates/accommodation-register.html
  src/main/resources/templates/index.html
  src/main/resources/templates/my-accommodation-list.html
  src/main/resources/templates/my-reservation-list.html
Labels: refactor 🛠️

#92 feat[#90] 예약 관리 - 예약 확정 / 취소 기능
  src/main/java/com/simsasookbak/reservation/controller/ReservationApiController.java
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
  src/main/java/com/simsasookbak/reservation/service/ReservationService.java
  src/main/resources/static/js/reservationList.js
  src/main/resources/templates/list-page.html
  src/main/resources/templates/reservation-management.html
Labels: feat🚀

#94 refactor : 숙박업자 예약 내역 화면 공통 레이아웃 및 정렬
  src/main/resources/templates/reservation-management.html
Labels: refactor 🛠️

#96 feat: 유저 권한 설정
  src/main/java/com/simsasookbak/global/config/WebSecurityConfig.java
  src/main/java/com/simsasookbak/member/domain/Member.java
  src/main/java/com/simsasookbak/member/domain/MemberDto.java
  src/main/java/com/simsasookbak/member/domain/Role.java
  src/main/java/com/simsasookbak/member/service/MemberService.java
  src/main/resources/data.sql
  src/main/resources/templates/layout/navigation-bar.html
Labels: enhancement, feat🚀

#98 feat : 예약, 숙소, 객실 관리 aop
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/global/aop/MethodExecutionRestrictionAspect.java
  src/main/java/com/simsasookbak/global/aop/MethodInvocationLimit.java
  src/main/java/com/simsasookbak/global/exception/GlobalExceptionHandler.java
  src/main/java/com/simsasookbak/global/exception/MethodInvocationLimitException.java
  src/main/java/com/simsasookbak/reservation/controller/ReservationController.java
  src/main/java/com/simsasookbak/room/controller/RoomController.java
  src/main/resources/templates/accommodation-register.html
  src/main/resources/templates/accommodation-update.html
  src/main/resources/templates/reservationPage.html
  src/main/resources/templates/room-update.html
Labels: enhancement, feat🚀

#99 refactor : s3 버킷명 수정
  src/main/java/com/simsasookbak/accommodation/domain/AccommodationImage.java
  src/main/java/com/simsasookbak/review/controller/ReviewController.java
  src/main/java/com/simsasookbak/review/service/ReviewService.java
  src/main/resources/application.yml
Labels: refactor 🛠️

#106 feat : 숙소 이미지 수정
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationImageRepository.java
  src/main/resources/templates/accommodation-register.html
  src/main/resources/templates/accommodation-update.html
Labels: enhancement, feat🚀

#109 feat: 권한 재설정 및 잔 버그 해결
  src/main/java/com/simsasookbak/global/config/WebSecurityConfig.java
  src/main/java/com/simsasookbak/member/controller/MemberController.java
  src/main/java/com/simsasookbak/member/controller/MyPageController.java
  src/main/java/com/simsasookbak/member/domain/Member.java
  src/main/java/com/simsasookbak/member/domain/MemberDto.java
  src/main/java/com/simsasookbak/member/domain/MemberRequestDto.java
  src/main/java/com/simsasookbak/member/repository/MemberRepository.java
  src/main/java/com/simsasookbak/member/service/MemberService.java
  src/main/java/com/simsasookbak/member/service/UserDetailService.java
  src/main/resources/static/js/mypage.js
  src/main/resources/static/js/register.js
  src/main/resources/templates/mypageInfo.html
Labels: enhancement, feat🚀

#110 Feature/admin page
  src/main/java/com/simsasookbak/member/controller/AdminController.java
  src/main/java/com/simsasookbak/member/service/AdminService.java
  src/main/resources/static/css/adminPage.css
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/js/adminPage.js
  src/main/resources/templates/adminPage.html
Labels: refactor 🛠️

#111 fix: 로그인 시, 상태 체크 변경
  src/main/java/com/simsasookbak/member/controller/MemberController.java
  src/main/java/com/simsasookbak/member/controller/MyPageController.java
  src/main/java/com/simsasookbak/member/domain/Member.java
  src/main/java/com/simsasookbak/member/domain/Status.java
  src/main/java/com/simsasookbak/member/repository/MemberRepository.java
  src/main/java/com/simsasookbak/member/service/MemberService.java
  src/main/java/com/simsasookbak/member/service/UserDetailService.java
Labels: bug

#112 Update README.md
  README.md
Labels: documentation

#115 feat: 숙소 상세 페이지 thymeleaf 적용
  src/main/resources/templates/details.html
  src/main/resources/templates/list-page.html
  src/main/resources/templates/my-accommodation-list.html
  src/main/resources/templates/reservation-management.html
Labels: enhancement

#116 refactor : "관리자 페이지 delete 수정"
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/java/com/simsasookbak/member/service/AdminService.java
  src/main/resources/static/js/adminPage.js
Labels: refactor 🛠️

#117 chore : deploy.sh 내 환경 변수 주입
  scripts/deploy.sh
Labels: chore🥷🏻

#118 fix : 템플릿 경로 변경
  src/main/java/com/simsasookbak/email/service/MailService.java
  src/main/resources/application.yml
  src/main/resources/templates/accommodation-register.html
  src/main/resources/templates/accommodation-update.html
  src/main/resources/templates/adminPage.html
  src/main/resources/templates/details.html
  src/main/resources/templates/index.html
  src/main/resources/templates/list-page.html
  src/main/resources/templates/my-accommodation-list.html
  src/main/resources/templates/my-reservation-list.html
  src/main/resources/templates/mypageInfo.html
  src/main/resources/templates/reservation-management.html
  src/main/resources/templates/reservationPage.html
  src/main/resources/templates/review-register.html
  src/main/resources/templates/room-update.html
  src/main/resources/templates/updateReservationPage.html
Labels: bug, chore🥷🏻

#123 Bug/update bug
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/templates/my-accommodation-list.html
  src/main/resources/templates/mypageInfo.html
Labels: bug

#128 feat[#127] update review
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/review/controller/ReviewController.java
  src/main/java/com/simsasookbak/review/domain/Review.java
  src/main/java/com/simsasookbak/review/dto/ReviewDto.java
  src/main/java/com/simsasookbak/review/repository/ReviewImageRepository.java
  src/main/java/com/simsasookbak/review/repository/ReviewRepository.java
  src/main/java/com/simsasookbak/review/service/ReviewService.java
  src/main/resources/templates/details.html
  src/main/resources/templates/review-register.html
Labels: feat🚀

#129 feat: 관리자페이지 권한 변경 기능 추가
  src/main/java/com/simsasookbak/member/controller/AdminController.java
  src/main/java/com/simsasookbak/member/domain/Member.java
  src/main/java/com/simsasookbak/member/service/AdminService.java
  src/main/resources/static/js/adminPage.js
  src/main/resources/templates/adminPage.html
Labels: refactor 🛠️

#136 feat: 상세페이지 댓글삭제+ 버튼 배치 약간수정
  src/main/java/com/simsasookbak/review/controller/ReviewController.java
  src/main/java/com/simsasookbak/review/service/ReviewService.java
  src/main/resources/static/css/style.css
  src/main/resources/static/js/review.js
  src/main/resources/templates/details.html
  src/main/resources/templates/layout/head.html
Labels: enhancement, feat🚀

#138 refactor : 상세 화면
  src/main/java/com/simsasookbak/accommodation/dto/AccommodationDto.java
  src/main/java/com/simsasookbak/accommodation/service/AccommodationService.java
  src/main/java/com/simsasookbak/review/repository/ReviewRepository.java
  src/main/java/com/simsasookbak/review/service/ReviewService.java
  src/main/resources/templates/details.html
Labels: refactor 🛠️

#139 Feature/프론트 수정
  README.md
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/review/domain/Review.java
  src/main/java/com/simsasookbak/review/dto/ReviewDto.java
  src/main/java/com/simsasookbak/review/service/ReviewService.java
  src/main/resources/data.sql
Labels: documentation, refactor 🛠️

#140 refactor : 숙소 이미지 필드 추가
  src/main/java/com/simsasookbak/accommodation/dto/response/AccommodationResponse.java
  src/main/java/com/simsasookbak/accommodation/dto/response/AccommodationView.java
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
  src/main/java/com/simsasookbak/review/service/ReviewService.java
Labels: refactor 🛠️

#142 comment : 메인 화면 문구 추가
  src/main/resources/templates/index.html
  src/main/resources/templates/room.png
Labels: refactor 🛠️

#137 Update README.md
  README.md
Labels: documentation

#145 Refactor/리뷰수정
  README.md
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
Labels: documentation

#148 feat: 검색 결과가 없을 때 페이지네이션 미표시
  src/main/resources/templates/adminPage.html
  src/main/resources/templates/list-page.html
Labels: enhancement

#152 Update README.md
  README.md
Labels: documentation

#154 Update README.md
  README.md
Labels: documentation

#155 Update README.md
  README.md
Labels: documentation

#158 docs : update README.md
  README.md
Labels: documentation

#159 docs : update README.md
  README.md
Labels: documentation

#160 docs : update README.md
  README.md
Labels: documentation

#162 Update README.md
  README.md
Labels: documentation

#164 fix : data.sql 수정
  src/main/resources/data.sql
Labels: bug

#163 Update README.md
  README.md
Labels: documentation

#165 Update README.md
  README.md
Labels: documentation

#168 Update README.md
  README.md
Labels: documentation

#167 fix: 숙소 리스트 사진 thymeleaf 수정
  src/main/resources/templates/list-page.html
Labels: bug

#169 bug: list page에 호텔 사진 노출
  src/main/resources/templates/details.html
  src/main/resources/templates/list-page.html
Labels: bug

#171 Update README.md
  README.md
Labels: documentation

#172 Update README.md
  README.md
Labels: documentation

#174 refactor : 잘못 할당한 변수 고침
  src/main/java/com/simsasookbak/SimsasookbakApplication.java
  src/main/java/com/simsasookbak/accommodation/domain/Accommodation.java
  src/main/java/com/simsasookbak/global/aop/MethodExecutionRestrictionAspect.java
Labels: enhancement, feat🚀

#175 Develop
  src/main/java/com/simsasookbak/SimsasookbakApplication.java
  src/main/java/com/simsasookbak/accommodation/domain/Accommodation.java
  src/main/java/com/simsasookbak/global/aop/MethodExecutionRestrictionAspect.java
  src/main/java/com/simsasookbak/member/service/AdminService.java
Labels: bug

#177 Feature/redirect accom
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/member/controller/AdminController.java
  src/main/java/com/simsasookbak/review/controller/ReviewController.java
  src/main/resources/static/js/adminPage.js
  src/main/resources/static/js/review.js
  src/main/resources/templates/accommodation-update.html
  src/main/resources/templates/details.html
Labels: enhancement

#179 Develop
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/java/com/simsasookbak/member/controller/AdminController.java
  src/main/java/com/simsasookbak/review/controller/ReviewController.java
  src/main/resources/static/js/adminPage.js
  src/main/resources/static/js/review.js
  src/main/resources/templates/accommodation-update.html
  src/main/resources/templates/details.html
Labels: enhancement

#178 Update README.md
  README.md
Labels: documentation

#180 fix : 숙소 목록 검색
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
  src/main/java/com/simsasookbak/external/youtube/exception/YoutubeExceptionHandler.java
  src/main/resources/templates/list-page.html
Labels: bug

#181 fix : 숙소 목록 테이블 소문자로 변경
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
Labels: bug

#182 fix : 숙소 목록 검색
  src/main/java/com/simsasookbak/accommodation/repository/AccommodationRepository.java
  src/main/java/com/simsasookbak/external/youtube/exception/YoutubeExceptionHandler.java
  src/main/resources/templates/list-page.html
Labels: bug

#184 feat: 예약승인 받아야만 후기 등록
  src/main/java/com/simsasookbak/accommodation/controller/AccommodationController.java
  src/main/resources/templates/details.html
Labels: enhancement, feat🚀

#185 fix : 예약 내역이 없으면 리뷰 등록 버튼 미 노출
  src/main/java/com/simsasookbak/reservation/repository/ReservationRepository.java
  src/main/java/com/simsasookbak/reservation/service/ReservationService.java
  src/main/resources/templates/details.html
Labels: bug

#187 fix : details.html
  src/main/resources/templates/details.html
Labels: bug

#199 Refactor/detail fix
  src/main/java/com/simsasookbak/accommodation/dto/response/AccommodationResponse.java
  src/main/java/com/simsasookbak/external/ai/alan/event/AlanEventListener.java
  src/main/java/com/simsasookbak/global/page/controller/PageController.java
  src/main/resources/data.sql
  src/main/resources/templates/list-page.html
  src/main/resources/templates/reservationPage.html
Labels: refactor 🛠️
